apiVersion: v1
kind: Service
metadata:
  labels:
    app: mock-http-thermometer
  name: thermometer
  namespace: devices
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: 11111
  selector:
    app: mock-http-thermometer
  type: LoadBalancer
