apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-lwm2m
  namespace: deviceshifu
data:
#    device name and image address
  customInstructionsPython: |
    int: raw_value
    string: raw_value
  driverProperties: |
    driverSku: LwM2M Device
    driverImage: lwm2m-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      int:
        protocolPropertyList:
          MQTTTopic: "/test/topic1"
        gatewayPropertyList:
          ObjectId: /3442/0/120
          DataType: int
      string:
        protocolPropertyList:
          MQTTTopic: "/test/topic1"
        gatewayPropertyList:
          ObjectId: /3442/0/110
          DataType: string
