apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-lwm2m-coap
  name: deviceshifu-lwm2m-coap
  namespace: deviceshifu
spec:
  ports:
    - name: deviceshifu
      port: 80
      protocol: TCP
      nodePort: 30380
      targetPort: 8080
    - name: lwm2mserver-coap
      port: 5683
      protocol: UDP
      nodePort: 30300
      targetPort: 5683
  selector:
    app: deviceshifu-lwm2m-coap-deployment
  type: NodePort