apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-lwm2m-mock-deployment
  name: deviceshifu-lwm2m-mock-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-lwm2m-mock-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-lwm2m-mock-deployment
    spec:
      containers:
        - image: edgenesis/lwm2m-demo-deviceshifu-http-lwm2m:nightly-20240612
          name: deviceshifu-lwm2m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-lwm2m-mock"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: LOG_LEVEL
              value: debug
        - image: edgenesis/lwm2m-demo-gateway-lwm2m:nightly-20240612
          name: gateway-lwm2m
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-lwm2m-mock"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: deviceshifu-lwm2m-mock
      serviceAccountName: edgedevice-sa
