apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-thermometer-deployment
  name: deviceshifu-thermometer
  namespace: deviceshifu
spec:
  ports:
  - name: deviceshifu
    port: 80
    protocol: TCP
    nodePort: 30180
    targetPort: 8080
  selector:
    app: deviceshifu-thermometer-deployment
  type: NodePort
