apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-mqtt-customized
  namespace: devices
spec:
  sku: "MQTT Device"
  connection: Ethernet
  address: mosquitto-service.devices.svc.cluster.local:18830
  protocol: MQTT
  protocolSettings:
  gatewaySettings:
    protocol: lwm2m
    address: 192.168.50.106:5684 # edit it to lwm2m server address
    LwM2MSettings:
      endpointName: my-test-device
      securityMode: DTLS
      dtlsMode: PSK
      cipherSuites:
        - TLS_PSK_WITH_AES_128_CCM_8
      pskIdentity: test-id
      pskKey: ABC123
