apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-mqtt-customized
  namespace: deviceshifu
data:
#    device name and image address
  customInstructionsPython: |
    angle/x: XAngle
    angle/y: YAngle
  driverProperties: |
    driverSku: MQTT Device
    driverImage: mqtt-device:v0.0.1
#    available instructions
  instructions: |
    instructions:
      angle/x:
        protocolPropertyList:
          MQTTTopic: "/test/topic1"
        gatewayPropertyList:
          ObjectId: /3442/0/1130/0
          DataType: float
      angle/y:
        protocolPropertyList:
          MQTTTopic: "/test/topic1"
        gatewayPropertyList:
          ObjectId: /3442/0/1130/1
          DataType: float
