apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-mqtt-customized-deployment
  name: deviceshifu-mqtt-customized-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-mqtt-customized-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-mqtt-customized-deployment
    spec:
      containers:
        - image: edgenesis/lwm2m-demo-deviceshifu-http-mqtt-customized:nightly
          name: deviceshifu-mqtt
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-lwm2m"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - image: edgenesis/lwm2m-demo-gateway-lwm2m:nightly-20240612
          name: gateway-lwm2m
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-lwm2m"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: deviceshifu-lwm2m
      serviceAccountName: edgedevice-sa
