apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-mqtt-customized
  namespace: devices
spec:
  sku: "MQTT Device"
  connection: Ethernet
  address: mosquitto-service.devices.svc.cluster.local:31883
  protocol: MQTT
  protocolSettings:
  gatewaySettings:
    protocol: lwm2m
    address: leshan.eclipseprojects.io:5684 # edit it to lwm2m server address
    LwM2MSettings:
      endpointName: test-mqtt-connector
      securityMode: DTLS
      dtlsMode: PSK
      cipherSuites:
        - TLS_PSK_WITH_AES_128_CCM_8
      pskIdentity: test-id-mqtt-connector
      pskKey: ABC123
